function r = Chisq3(a,b,c,as,bs,cs,sigmax,sigmay,sigmaz);

% sigmax = sqrt(sigmaa^2*(b*c)^2 +sigmab^2*(a*c)^2 + sigmac^2*(a*b)^2);
% sigmay = sqrt(sigmaa^2*(2*a)^2 + (sigmab^2)*(2*b)^2 + sigmac^2*(2*c)^2);
% sigmaz = sqrt(sigmaa^2 + sigmab^2 + sigmac^2);
r = ((a-as).*(b.^2.*c.^2./sigmax.^2+4.*a.^2./sigmay.^2+1./sigmaz.^2)+...
    (b-bs).*(b.*c.^2./sigmax.^2.*a+4.*a./sigmay.^2.*b+1./sigmaz.^2)+... 
    (c-cs).*(b.^2.*c./sigmax.^2.*a+4.*a./sigmay.^2.*c+1./sigmaz.^2)).*(a-as)+...
((a-as).*(b.*c.^2./sigmax.^2.*a+...
    4.*a./sigmay.^2.*b+1./sigmaz.^2)+(b-bs).*(a.^2.*c.^2./sigmax.^2+4.*b.^2./sigmay.^2+1./sigmaz.^2)+...
    (c-cs).*(a.^2.*c./sigmax.^2.*b+4.*b./sigmay.^2.*c+1./sigmaz.^2)).*(b-bs)+...
    ((a-as).*(b.^2.*c./sigmax.^2.*a+4.*a./sigmay.^2.*c+1./sigmaz.^2)+...
(b-bs).*(a.^2.*c./sigmax.^2.*b+4.*b./sigmay.^2.*c+...
1./sigmaz.^2)+(c-cs).*(a.^2.*b.^2./sigmax.^2+4.*c.^2./sigmay.^2+1./sigmaz.^2)).*(c-cs);

    