function s = Chisq2(a,b,c,as,bs,cs,sigmax,sigmay,sigmaz);

s = ((a-as).*(b.^2.*c.^2./sigmax.^2+4.*a.^2./sigmay.^2+1./sigmaz.^2)+(b-bs).*(b.*(c.^2)./sigmax.^2.*a+4.*a./sigmay.^2.*b+...
    1./sigmaz.^2)).*(a-as)+((a-as).*(b.*c.^2./sigmax.^2.*a+4.*a./sigmay.^2.*b+1./sigmaz.^2)+(b-bs).*(a.^2.*c.^2./sigmax.^2+...
    4.*b.^2./sigmay.^2+1./sigmaz.^2)).*(b-bs);